trigger:
  branches:
    include:
      - main
      - dev
variables:
- group: BuildVariables
- group: SupabaseVariables
- group: APIsUrlsVariables
- group: ElasticSearchVariables
- name: dockerfilePath
  value: '**/Dockerfile'

- ${{if eq( variables['Build.SourceBranchName'], 'main' ) }}:
  - name: StorageInfo.UrlBase
    value: $(StorageEndpoint)
  - name: StorageInfo.StorageEndpoint
    value: $(UrlBase)
  - name: StorageInfo.ApiKey
    value: $(ApiKey)
  - name: StorageInfo.AnonKey
    value: $(AnonToken)
  - name: ElasticConfiguration.Uri
    value: $(ElasticUri)
  - name: ElasticConfiguration.Username
    value: $(ElasticUsername)    
  - name: ElasticConfiguration.Password
    value: $(ElasticPassword)    
  - name: ElasticConfiguration.DefaultIndex
    value: $(ElasticDefaultIndex)

- ${{if eq( variables['Build.SourceBranchName'], 'dev' ) }}:
  - name: StorageInfo.UrlBase
    value: $(StorageEndpoint)
  - name: StorageInfo.StorageEndpoint
    value: $(UrlBase)
  - name: StorageInfo.ApiKey
    value: $(ApiKey)
  - name: StorageInfo.AnonKey
    value: $(AnonKey)
  - name: ElasticConfiguration.Uri
    value: $(ElasticUri)
  - name: ElasticConfiguration.Username
    value: $(ElasticUsername)    
  - name: ElasticConfiguration.Password
    value: $(ElasticPassword)    
  - name: ElasticConfiguration.DefaultIndex
    value: $(ElasticDefaultIndex)

jobs:
- job: Build
  pool:
    name: $(BuildPoolName)
  steps:
    - task: UseDotNet@2
      displayName: Using .NET 7.0
      inputs:
        packageType: 'sdk'
        version: '7.0.x'
        includePreviewVersions: true
    
    - task: DotNetCoreCLI@2
      displayName: Restoring packages
      inputs: 
        command: restore
        projects: '**/*.csproj'
    
    - task: DotNetCoreCLI@2
      displayName: Building Solution
      inputs:
        command: build
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Running tests
      inputs:
        command: test
        projects: '**/*[Tt]est*.csproj'
        publishTestResults: true
    
    - task: DotNetCoreCLI@2
      displayName: Running publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: False
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

    - task: FileTransform@1
      inputs:
        folderPath: '$(build.artifactstagingdirectory)/ApiStorageManager.WebApi/'
        fileType: 'json'
        targetFiles: 'appsettings.json'

    - task: CopyFiles@2
      displayName: Copying Dockerfiles
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/src/ApiStorageManager.WebApi/'
        Contents: '[Dd]ocker*'
        TargetFolder: '$(build.artifactstagingdirectory)/ApiStorageManager.WebApi'
    
    - task: PublishBuildArtifacts@1
      displayName: Publish artifacts
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'